repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      -   id: check-xml
      -   id: check-yaml

      -   id: end-of-file-fixer
      -   id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^(src/.*\.py|scripts/.*\.py|.*\.py)$

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=88"]
        files: ^(src/.*\.py|scripts/.*\.py|.*\.py)$

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1  # Use the latest version
    hooks:
      - id: autopep8
        args: ["--max-line-length=88","--in-place"]
        files: ^(src/.*\.py|scripts/.*\.py|.*\.py)$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
