version: 1.0.{build}
image: Visual Studio 2022

environment:
  FORCE_COLOR: "1"
  matrix:
    - target: "Windows"
      platform: "x64"
      output-format: "app"
    - target: "macOS"
      platform: "x64"
      output-format: "app"
    - target: "Ubuntu-24.04"
      platform: "Linux"
      output-format: "system"
      pre-command: "sudo apt -y install socat"
      briefcase-run-prefix: "xvfb-run"
      briefcase-args: "--target ubuntu:24.04"
    - target: "Fedora-40"
      platform: "Linux"
      output-format: "system"
      pre-command: "sudo apt -y install socat"
      briefcase-run-prefix: "xvfb-run"
      briefcase-args: "--target fedora:40"

matrix:
  fast_finish: false

build_script:
  - ps: |
      if ($env:target -eq "macOS") {
        Set-AppveyorBuildWorkerImage "macos"
      }
      elseif ($env:target -eq "Ubuntu-24.04" -or $env:target -eq "Fedora-40") {
        Set-AppveyorBuildWorkerImage "ubuntu-latest"
      }

  # Checkout
  - cmd: git clone https://github.com/Unit1208/HordeQT.git

  # Setup Python
  - ps: |
      if ($env:platform -eq "Linux" -or $env:platform -eq "macOS") {
        sudo apt update
        sudo apt install -y python3 python3-pip
      }
      else {
        choco install python --version=3.12
      }
  
  # Install Briefcase
  - pip install -U pip setuptools wheel
  - pip install briefcase

  # Setup environment
  - ps: |
      if ($env:target -eq "Windows") {
        Write-Host "Windows environment setup"
      }
      elseif ($env:target -eq "macOS") {
        Write-Host "macOS environment setup"
        echo $JAVA_HOME_17_X64 | Out-File -Append -FilePath env-vars.txt
      }
      else {
        sudo apt -y install socat
      }

  # Build App
  - ps: |
      & briefcase build `
        --target $env:target `
        --output-format $env:output-format `
        --no-input `
        $env:briefcase-args


  # Package App
  - ps: |
      & briefcase package `
        --target $env:target `
        --output-format $env:output-format `
        --no-input `
        $env:briefcase-package-prefix `
        $env:briefcase-args

artifacts:
  - path: dist/*
    name: App-${env:target}

on_failure:
  - cmd: echo "Build failed! Uploading logs."
  - cmd: copy logs/* to failure-logs/
  - path: failure-logs/*
    name: Log-Failure-${env:target}
