version: 1.0.{build}
image:
  - "Visual Studio 2022"
  - "Ubuntu"
  - "macOS"

environment:
  FORCE_COLOR: "1"
build_script:
  # Checkout
  - cmd: git clone https://github.com/Unit1208/HordeQT.git

  # Setup environment depending on platform
  - ps: |
      if ($env:platform -eq "Windows") {
        choco install python --version=3.12
      }
      elseif ($env:platform -eq "macOS") {
        echo "Setting up macOS environment"
        brew install python@3.12
      }
      elseif ($env:platform -eq "Ubuntu-24.04") {
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv
      }

  # Build App
  - ps: python build.py

artifacts:
  - path: dist/*
    name: App-${env:target}
