version: 1.3.1-{build}
image:
- Ubuntu2204
- Visual Studio 2022
  # - "macOS"

environment:
  FORCE_COLOR: '1'
build_script:
  # Checkout
- cmd: git clone https://github.com/Unit1208/HordeQT.git

  # Setup environment depending on platform
- ps: |
    if ($env:OS -eq "Windows_NT") {
      choco install python --version=3.12.6
    }
- sh: |
    if [ "$(uname)" = "Darwin" ]; then
      brew install python@3.12
    elif [ "$(uname)" = "Linux" ]; then
      sudo apt update
      sudo apt install python3.10-dev python3.10-venv python3.10-full python3-pip python-is-python3 -y
      alias python=/usr/bin/python
    fi

  # Build App
- ps: python build.py
- sh: |
    if [ "$(uname)" = "Linux" ]; then
      sudo rm build/ -rf
      sudo chmod -R 777 dist/

    fi


artifacts:
- path: dist/HordeQT-*.flatpak
  name: HordeQT-Linux
- path: dist/*.msi
  name: HordeQT-Windows-msi
  # - path: build/hordeqt/windows/app/src/HordeQT.exe
  #   name: HordeQT-Windows-exe
