# AppVeyor CI configuration file

version: 1.0.{build}

image:
  - Ubuntu2204
  - Visual Studio 2022
  - MacOS

platform:
  - x64

# Install dependencies
install:
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Ubuntu2204') {
        sudo apt-get update
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt-get install -y python3.12 ccache libpython3.12-dev pipx
        python -m venv venv
        source venv/bin/activate
      }

  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'MacOS') {
        brew install python@3.12
        python -m venv venv
        source venv/bin/activate

      }

  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2022') {
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop bucket add main
        scoop install main/python
        python -m venv venv
        call venv\scripts\activate.bat
      }



build_script:
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Ubuntu2204') {
        /home/appveyor/.local/bin/poetry run build

      }

  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'MacOS') {
        /Users/appveyor/.local/bin/poetry run build

      }

  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2022') {
        pipx run poetry run build


      }
  # Conditional artifact pushing
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Ubuntu2204') {
        appveyor PushArtifact "hordeqt_py/__main__.bin" -FileName "HordeQT-Linux.bin"
      } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'macos-12') {
        appveyor PushArtifact "hordeqt_py/HordeQT.app" -FileName "HordeQT-Mac.app"
      } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -match 'Visual Studio') {
        appveyor PushArtifact "horde_qt\\__main__.exe" -FileName "HordeQT-Windows.exe"
      }

artifacts:
  # Placeholder in case automatic artifact pushing is not triggered.
  - path: hordeqt_py/__main__.bin
  - path: hordeqt_py/HordeQT.app
  - path: horde_qt\__main__.exe
