version: 1.0.{build}
image:
  - "Visual Studio 2022"
  - "Ubuntu2204"
  - "macOS"

environment:
  FORCE_COLOR: "1"
build_script:
  # Checkout
  - cmd: git clone https://github.com/Unit1208/HordeQT.git

  # Setup environment depending on platform
  - ps: |
      if ($env:OS -eq "Windows_NT") {
        choco install python --version=3.12.6
      }
  - sh: |
      if [ "$(uname)" = "Darwin" ]; then
        brew install python@3.12
      elif [ "$(uname)" = "Linux" ]; then
        sudo apt update
        sudo apt install python3.11-dev python3.11-venv python3.11-full python3-pip -y
      fi

  # Build App
  - ps: python build.py

artifacts:
  - path: dist/*
    name: App-${env:target}
