# AppVeyor CI configuration file

version: 1.0.{build}

image:
  - Ubuntu2204
  - Visual Studio 2022
  - MacOS

platform:
  - x64

# Install dependencies
install:
  - pipx install poetry
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Ubuntu2204') {
        sudo apt-get update
        sudo apt-get install -y python3 ccache libpython3-dev pipx
        pipx ensurepath
        pipx install poetry
        $env:PATH = "$HOME\.local\bin;$env:PATH"

      }

  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'MacOS') {
        brew install python pipx
        pipx ensurepath
        curl -sSL https://install.python-poetry.org | python3 -
        $env:PATH = "$HOME\.local\bin;$env:PATH"
      }

  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2022') {
        scoop bucket add main
        scoop install main/python
        scoop install main/pipx
        pipx ensurepath
        pipx install poetry
        $env:PATH = "$env:APPDATA\Python\Scripts;$env:PATH"
      }

  # Install project dependencies using poetry
  - poetry install

build_script:
  # Build the project using poetry
  - poetry run build

  # Conditional artifact pushing
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Ubuntu2204') {
        appveyor PushArtifact "hordeqt_py/HordeQT.bin" -FileName "HordeQT-Linux.bin"
      } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'macos-12') {
        appveyor PushArtifact "hordeqt_py/HordeQT.app" -FileName "HordeQT-Mac.app"
      } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -match 'Visual Studio') {
        appveyor PushArtifact "horde_qt\\__main__.exe" -FileName "HordeQT-Windows.exe"
      }

artifacts:
  # Placeholder in case automatic artifact pushing is not triggered.
  - path: hordeqt_py/HordeQT.bin
  - path: hordeqt_py/HordeQT.app
  - path: horde_qt\__main__.exe
