version: 1.0.{build}
image:
  - "Visual Studio 2022"
  - "Ubuntu"
  - "macOS"

environment:
  FORCE_COLOR: "1"
build_script:
  # Checkout
  - cmd: git clone https://github.com/Unit1208/HordeQT.git

  # Setup environment depending on platform
  - ps: |
      echo "$env:platform"
      if ($env:platform -eq "Windows") {
        choco install python --version=3.12
      }
      elseif ($env:platform -eq "macOS") {
        echo "Setting up macOS environment"
        brew install python@3.12
      }
      elseif ($env:platform -eq "Linux") {
        sudo apt update
        sudo apt install software-properties-common -y
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install python3.12-dev python3.12-venv python3.12-full
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12 
      }

  # Build App
  - ps: python build.py

artifacts:
  - path: dist/*
    name: App-${env:target}
