name: Build Application (Macos)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -


      - name: Cache Poetry dependencies

      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install

      - name: Build application
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: HordeQt-macos
          path: |
            hordeqt_py/dist/mainwindow.bin
          if-no-files-found: ignore
