name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11,3.12]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            curl -sSL https://install.python-poetry.org | python -
          else
            curl -sSL https://install.python-poetry.org | python3 -
          fi

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.virtualenvs
            C:\Users\runneradmin\AppData\Local\pypoetry\Cache
            C:\Users\runneradmin\AppData\Local\pypoetry\Virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            set PATH=C:\Users\runneradmin\.local\bin;%PATH%
            poetry install
          else
            export PATH="$HOME/.local/bin:$PATH"
            poetry install
          fi

      - name: Build application
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            set PATH=C:\Users\runneradmin\.local\bin;%PATH%
            poetry run build
          else
            export PATH="$HOME/.local/bin:$PATH"
            poetry run build
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mainwindow-${{ matrix.os }}
          path: |
            hordeqt_py/dist/mainwindow.exe
            hordeqt_py/dist/mainwindow.bin
          if-no-files-found: ignore
